export const SORT_BY_NAME_ASC = 'SORT_BY_NAME_ASC'
export const SORT_BY_NAME_DESC = 'SORT_BY_NAME_DESC'
export const SORT_BY_AMOUNT_ASC = 'SORT_BY_AMOUNT_ASC'
export const SORT_BY_AMOUNT_DESC = 'SORT_BY_AMOUNT_DESC'
